application: starlit-tine-552
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.homeapp

- url: /makerecord
  script: main.recapp

- url: /news
  script: main.newsapp

libraries:
- name: webapp2
  version: "2.5.2"
